name: disasternow
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  http: ^1.3.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/disaster_now_logo.png
    - assets/images/loading_custom.gif
    - assets/images/button_next.png
    - assets/images/map.png
    - assets/images/icon1.png
    - assets/images/icon2.png
    - assets/images/icon3.png
    - assets/images/icon4.png
    - assets/images/icon5.png
    - assets/images/close_button.png
    - assets/images/map2.png
    - assets/images/noti1.png
    - assets/images/aduan1.png
    - assets/images/aduan2.png
    - assets/images/aduan3.png
    - assets/images/noti2.png
    - assets/images/cari1.png
    - assets/images/cari2.png
    - assets/images/cari3.png
    - assets/images/noti3.png
    - assets/malaysia.geojson
    - assets/images/layer.png
    - assets/images/zoomIn.png
    - assets/images/zoomOut.png
    - assets/images/home.png
    - assets/images/basemap.png
    - assets/images/navbar.png
    - assets/images/notifikasi.png
    - assets/images/utama.png
    - assets/images/carta.png
    - assets/images/pengenalan.png
    - assets/images/rectangle.png
    - assets/images/osm_preview.png
    - assets/images/imagery_preview.png
    - assets/images/klik.png
    - assets/images/aduan.png
    - assets/images/search.png
    - assets/images/minta_bantuan.png
    - assets/images/beri_bantuan.png
